// Code generated by protoc-gen-go-messaging. DO NOT EDIT.

package dante_spb

// Service: DeadMessageQueryService
// Method: GetDeadMessage

// Method: ListDeadMessages

// Method: ListDeadMessageEvents
