// Code generated by protoc-gen-go-messaging. DO NOT EDIT.

package deployer_spb

// Service: DeploymentCommandService
// Method: TriggerDeployment

// Method: TerminateDeployment

// Method: UpsertEnvironment

// Method: UpsertStack
