// Code generated by protoc-gen-go-sugar. DO NOT EDIT.

package deployer_spb

type IsTriggerDeploymentRequest_Source = isTriggerDeploymentRequest_Source
type IsUpsertEnvironmentRequest_Src = isUpsertEnvironmentRequest_Src
