// Code generated by protoc-gen-go-sugar. DO NOT EDIT.

package deployer_spb

type IsTriggerDeploymentRequest_Source = isTriggerDeploymentRequest_Source
type IsTriggerDeploymentRequest_GithubSource_Ref = isTriggerDeploymentRequest_GithubSource_Ref
type IsUpsertEnvironmentRequest_Src = isUpsertEnvironmentRequest_Src
