// Code generated by protoc-gen-go-messaging. DO NOT EDIT.

package deployer_spb

// Service: DeploymentCommandService
// Method: TriggerDeployment

func (msg *TriggerDeploymentRequest) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service": "/o5.deployer.v1.service.DeploymentCommandService/TriggerDeployment",
		"grpc-message": "o5.deployer.v1.service.TriggerDeploymentRequest",
	}
	return headers
}
