// Code generated by protoc-gen-go-psm. DO NOT EDIT.

package deployer_spb

import (
	psm "github.com/pentops/protostate/psm"
)

// State Query Service for %sdeployment
type DeploymentPSMQuerySet = psm.StateQuerySet[
	*GetDeploymentRequest,
	*GetDeploymentResponse,
	*ListDeploymentsRequest,
	*ListDeploymentsResponse,
	*ListDeploymentEventsRequest,
	*ListDeploymentEventsResponse,
]

func NewDeploymentPSMQuerySet(
	smSpec psm.QuerySpec,
	options psm.StateQueryOptions,
) (*DeploymentPSMQuerySet, error) {
	return psm.BuildStateQuerySet[
		*GetDeploymentRequest,
		*GetDeploymentResponse,
		*ListDeploymentsRequest,
		*ListDeploymentsResponse,
		*ListDeploymentEventsRequest,
		*ListDeploymentEventsResponse,
	](smSpec, options)
}

// State Query Service for %sstack
type StackPSMQuerySet = psm.StateQuerySet[
	*GetStackRequest,
	*GetStackResponse,
	*ListStacksRequest,
	*ListStacksResponse,
	*ListStackEventsRequest,
	*ListStackEventsResponse,
]

func NewStackPSMQuerySet(
	smSpec psm.QuerySpec,
	options psm.StateQueryOptions,
) (*StackPSMQuerySet, error) {
	return psm.BuildStateQuerySet[
		*GetStackRequest,
		*GetStackResponse,
		*ListStacksRequest,
		*ListStacksResponse,
		*ListStackEventsRequest,
		*ListStackEventsResponse,
	](smSpec, options)
}
