// Code generated by protoc-gen-go-messaging. DO NOT EDIT.

package deployer_spb

// Service: DeploymentQueryService
// Method: GetDeployment

// Method: ListDeploymentEvents

// Method: ListDeployments

// Method: GetStack

// Method: ListStacks

// Method: ListStackEvents

// Method: ListEnvironments

// Method: GetEnvironment

// Method: ListEnvironmentEvents
