// Code generated by protoc-gen-go-messaging. DO NOT EDIT.

package builder_pb

// Service: BuilderTopic
// Method: BuildProto

func (msg *BuildProtoMessage) MessagingTopic() string {
	return "j5-builder-input"
}
func (msg *BuildProtoMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service": "/o5.builder.v1.BuilderTopic/BuildProto",
		"grpc-message": "o5.builder.v1.BuildProtoMessage",
	}
	return headers
}

// Method: BuildAPI

func (msg *BuildAPIMessage) MessagingTopic() string {
	return "j5-builder-input"
}
func (msg *BuildAPIMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service": "/o5.builder.v1.BuilderTopic/BuildAPI",
		"grpc-message": "o5.builder.v1.BuildAPIMessage",
	}
	return headers
}
