// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: o5/dante/v1/dead_message.proto

package dante_pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	auth_pb "github.com/pentops/o5-go/auth/v1/auth_pb"
	_ "github.com/pentops/protostate/gen/v1/psm_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageStatus int32

const (
	MessageStatus_MESSAGE_STATUS_UNSPECIFIED MessageStatus = 0
	MessageStatus_MESSAGE_STATUS_CREATED     MessageStatus = 1
	MessageStatus_MESSAGE_STATUS_UPDATED     MessageStatus = 2
	MessageStatus_MESSAGE_STATUS_REPLAYED    MessageStatus = 3
	MessageStatus_MESSAGE_STATUS_REJECTED    MessageStatus = 4
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_UNSPECIFIED",
		1: "MESSAGE_STATUS_CREATED",
		2: "MESSAGE_STATUS_UPDATED",
		3: "MESSAGE_STATUS_REPLAYED",
		4: "MESSAGE_STATUS_REJECTED",
	}
	MessageStatus_value = map[string]int32{
		"MESSAGE_STATUS_UNSPECIFIED": 0,
		"MESSAGE_STATUS_CREATED":     1,
		"MESSAGE_STATUS_UPDATED":     2,
		"MESSAGE_STATUS_REPLAYED":    3,
		"MESSAGE_STATUS_REJECTED":    4,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_o5_dante_v1_dead_message_proto_enumTypes[0].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_o5_dante_v1_dead_message_proto_enumTypes[0]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_o5_dante_v1_dead_message_proto_rawDescGZIP(), []int{0}
}

type Urgency int32

const (
	Urgency_URGENCY_UNSPECIFIED Urgency = 0
	Urgency_URGENCY_LOW         Urgency = 1
	Urgency_URGENCY_MEDIUM      Urgency = 2
	Urgency_URGENCY_HIGH        Urgency = 3
)

// Enum value maps for Urgency.
var (
	Urgency_name = map[int32]string{
		0: "URGENCY_UNSPECIFIED",
		1: "URGENCY_LOW",
		2: "URGENCY_MEDIUM",
		3: "URGENCY_HIGH",
	}
	Urgency_value = map[string]int32{
		"URGENCY_UNSPECIFIED": 0,
		"URGENCY_LOW":         1,
		"URGENCY_MEDIUM":      2,
		"URGENCY_HIGH":        3,
	}
)

func (x Urgency) Enum() *Urgency {
	p := new(Urgency)
	*p = x
	return p
}

func (x Urgency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Urgency) Descriptor() protoreflect.EnumDescriptor {
	return file_o5_dante_v1_dead_message_proto_enumTypes[1].Descriptor()
}

func (Urgency) Type() protoreflect.EnumType {
	return &file_o5_dante_v1_dead_message_proto_enumTypes[1]
}

func (x Urgency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Urgency.Descriptor instead.
func (Urgency) EnumDescriptor() ([]byte, []int) {
	return file_o5_dante_v1_dead_message_proto_rawDescGZIP(), []int{1}
}

type DeadMessageState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId   string           `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status      MessageStatus    `protobuf:"varint,2,opt,name=status,proto3,enum=o5.dante.v1.MessageStatus" json:"status,omitempty"`
	CurrentSpec *DeadMessageSpec `protobuf:"bytes,3,opt,name=current_spec,json=currentSpec,proto3" json:"current_spec,omitempty"`
}

func (x *DeadMessageState) Reset() {
	*x = DeadMessageState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o5_dante_v1_dead_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeadMessageState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadMessageState) ProtoMessage() {}

func (x *DeadMessageState) ProtoReflect() protoreflect.Message {
	mi := &file_o5_dante_v1_dead_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadMessageState.ProtoReflect.Descriptor instead.
func (*DeadMessageState) Descriptor() ([]byte, []int) {
	return file_o5_dante_v1_dead_message_proto_rawDescGZIP(), []int{0}
}

func (x *DeadMessageState) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeadMessageState) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

func (x *DeadMessageState) GetCurrentSpec() *DeadMessageSpec {
	if x != nil {
		return x.CurrentSpec
	}
	return nil
}

type DeadMessageSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VersionId string `protobuf:"bytes,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	// The ID used by the underlying messaging infra, can be any format
	InfraMessageId string                 `protobuf:"bytes,2,opt,name=infra_message_id,json=infraMessageId,proto3" json:"infra_message_id,omitempty"`
	QueueName      string                 `protobuf:"bytes,3,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	GrpcName       string                 `protobuf:"bytes,4,opt,name=grpc_name,json=grpcName,proto3" json:"grpc_name,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Payload        *Any                   `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	// Types that are assignable to Problem:
	//
	//	*DeadMessageSpec_InvariantViolation
	//	*DeadMessageSpec_UnhandledError
	Problem isDeadMessageSpec_Problem `protobuf_oneof:"problem"`
}

func (x *DeadMessageSpec) Reset() {
	*x = DeadMessageSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o5_dante_v1_dead_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeadMessageSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadMessageSpec) ProtoMessage() {}

func (x *DeadMessageSpec) ProtoReflect() protoreflect.Message {
	mi := &file_o5_dante_v1_dead_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadMessageSpec.ProtoReflect.Descriptor instead.
func (*DeadMessageSpec) Descriptor() ([]byte, []int) {
	return file_o5_dante_v1_dead_message_proto_rawDescGZIP(), []int{1}
}

func (x *DeadMessageSpec) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *DeadMessageSpec) GetInfraMessageId() string {
	if x != nil {
		return x.InfraMessageId
	}
	return ""
}

func (x *DeadMessageSpec) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *DeadMessageSpec) GetGrpcName() string {
	if x != nil {
		return x.GrpcName
	}
	return ""
}

func (x *DeadMessageSpec) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeadMessageSpec) GetPayload() *Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (m *DeadMessageSpec) GetProblem() isDeadMessageSpec_Problem {
	if m != nil {
		return m.Problem
	}
	return nil
}

func (x *DeadMessageSpec) GetInvariantViolation() *InvariantViolation {
	if x, ok := x.GetProblem().(*DeadMessageSpec_InvariantViolation); ok {
		return x.InvariantViolation
	}
	return nil
}

func (x *DeadMessageSpec) GetUnhandledError() *UnhandledError {
	if x, ok := x.GetProblem().(*DeadMessageSpec_UnhandledError); ok {
		return x.UnhandledError
	}
	return nil
}

type isDeadMessageSpec_Problem interface {
	isDeadMessageSpec_Problem()
}

type DeadMessageSpec_InvariantViolation struct {
	InvariantViolation *InvariantViolation `protobuf:"bytes,10,opt,name=invariant_violation,json=invariantViolation,proto3,oneof"`
}

type DeadMessageSpec_UnhandledError struct {
	UnhandledError *UnhandledError `protobuf:"bytes,11,opt,name=unhandled_error,json=unhandledError,proto3,oneof"`
}

func (*DeadMessageSpec_InvariantViolation) isDeadMessageSpec_Problem() {}

func (*DeadMessageSpec_UnhandledError) isDeadMessageSpec_Problem() {}

type InvariantViolation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string  `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Error       *Any    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Urgency     Urgency `protobuf:"varint,3,opt,name=urgency,proto3,enum=o5.dante.v1.Urgency" json:"urgency,omitempty"`
}

func (x *InvariantViolation) Reset() {
	*x = InvariantViolation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o5_dante_v1_dead_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvariantViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvariantViolation) ProtoMessage() {}

func (x *InvariantViolation) ProtoReflect() protoreflect.Message {
	mi := &file_o5_dante_v1_dead_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvariantViolation.ProtoReflect.Descriptor instead.
func (*InvariantViolation) Descriptor() ([]byte, []int) {
	return file_o5_dante_v1_dead_message_proto_rawDescGZIP(), []int{2}
}

func (x *InvariantViolation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InvariantViolation) GetError() *Any {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *InvariantViolation) GetUrgency() Urgency {
	if x != nil {
		return x.Urgency
	}
	return Urgency_URGENCY_UNSPECIFIED
}

type UnhandledError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UnhandledError) Reset() {
	*x = UnhandledError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o5_dante_v1_dead_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnhandledError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnhandledError) ProtoMessage() {}

func (x *UnhandledError) ProtoReflect() protoreflect.Message {
	mi := &file_o5_dante_v1_dead_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnhandledError.ProtoReflect.Descriptor instead.
func (*UnhandledError) Descriptor() ([]byte, []int) {
	return file_o5_dante_v1_dead_message_proto_rawDescGZIP(), []int{3}
}

func (x *UnhandledError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Any wraps the well-known any, but encodes messages as JSON in addition
type Any struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proto *anypb.Any `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	Json  string     `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
}

func (x *Any) Reset() {
	*x = Any{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o5_dante_v1_dead_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Any) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Any) ProtoMessage() {}

func (x *Any) ProtoReflect() protoreflect.Message {
	mi := &file_o5_dante_v1_dead_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Any.ProtoReflect.Descriptor instead.
func (*Any) Descriptor() ([]byte, []int) {
	return file_o5_dante_v1_dead_message_proto_rawDescGZIP(), []int{4}
}

func (x *Any) GetProto() *anypb.Any {
	if x != nil {
		return x.Proto
	}
	return nil
}

func (x *Any) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type DeadMessageEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata  *Metadata             `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	MessageId string                `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Event     *DeadMessageEventType `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *DeadMessageEvent) Reset() {
	*x = DeadMessageEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o5_dante_v1_dead_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeadMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadMessageEvent) ProtoMessage() {}

func (x *DeadMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_o5_dante_v1_dead_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadMessageEvent.ProtoReflect.Descriptor instead.
func (*DeadMessageEvent) Descriptor() ([]byte, []int) {
	return file_o5_dante_v1_dead_message_proto_rawDescGZIP(), []int{5}
}

func (x *DeadMessageEvent) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DeadMessageEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeadMessageEvent) GetEvent() *DeadMessageEventType {
	if x != nil {
		return x.Event
	}
	return nil
}

type DeadMessageEventType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*DeadMessageEventType_Created_
	//	*DeadMessageEventType_Updated_
	//	*DeadMessageEventType_Replayed_
	//	*DeadMessageEventType_Rejected_
	Type isDeadMessageEventType_Type `protobuf_oneof:"type"`
}

func (x *DeadMessageEventType) Reset() {
	*x = DeadMessageEventType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o5_dante_v1_dead_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeadMessageEventType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadMessageEventType) ProtoMessage() {}

func (x *DeadMessageEventType) ProtoReflect() protoreflect.Message {
	mi := &file_o5_dante_v1_dead_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadMessageEventType.ProtoReflect.Descriptor instead.
func (*DeadMessageEventType) Descriptor() ([]byte, []int) {
	return file_o5_dante_v1_dead_message_proto_rawDescGZIP(), []int{6}
}

func (m *DeadMessageEventType) GetType() isDeadMessageEventType_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *DeadMessageEventType) GetCreated() *DeadMessageEventType_Created {
	if x, ok := x.GetType().(*DeadMessageEventType_Created_); ok {
		return x.Created
	}
	return nil
}

func (x *DeadMessageEventType) GetUpdated() *DeadMessageEventType_Updated {
	if x, ok := x.GetType().(*DeadMessageEventType_Updated_); ok {
		return x.Updated
	}
	return nil
}

func (x *DeadMessageEventType) GetReplayed() *DeadMessageEventType_Replayed {
	if x, ok := x.GetType().(*DeadMessageEventType_Replayed_); ok {
		return x.Replayed
	}
	return nil
}

func (x *DeadMessageEventType) GetRejected() *DeadMessageEventType_Rejected {
	if x, ok := x.GetType().(*DeadMessageEventType_Rejected_); ok {
		return x.Rejected
	}
	return nil
}

type isDeadMessageEventType_Type interface {
	isDeadMessageEventType_Type()
}

type DeadMessageEventType_Created_ struct {
	Created *DeadMessageEventType_Created `protobuf:"bytes,1,opt,name=created,proto3,oneof"`
}

type DeadMessageEventType_Updated_ struct {
	Updated *DeadMessageEventType_Updated `protobuf:"bytes,2,opt,name=updated,proto3,oneof"`
}

type DeadMessageEventType_Replayed_ struct {
	Replayed *DeadMessageEventType_Replayed `protobuf:"bytes,3,opt,name=replayed,proto3,oneof"`
}

type DeadMessageEventType_Rejected_ struct {
	Rejected *DeadMessageEventType_Rejected `protobuf:"bytes,4,opt,name=rejected,proto3,oneof"`
}

func (*DeadMessageEventType_Created_) isDeadMessageEventType_Type() {}

func (*DeadMessageEventType_Updated_) isDeadMessageEventType_Type() {}

func (*DeadMessageEventType_Replayed_) isDeadMessageEventType_Type() {}

func (*DeadMessageEventType_Rejected_) isDeadMessageEventType_Type() {}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Actor     *auth_pb.Actor         `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o5_dante_v1_dead_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_o5_dante_v1_dead_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_o5_dante_v1_dead_message_proto_rawDescGZIP(), []int{7}
}

func (x *Metadata) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Metadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Metadata) GetActor() *auth_pb.Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type DeadMessageEventType_Created struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spec *DeadMessageSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *DeadMessageEventType_Created) Reset() {
	*x = DeadMessageEventType_Created{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o5_dante_v1_dead_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeadMessageEventType_Created) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadMessageEventType_Created) ProtoMessage() {}

func (x *DeadMessageEventType_Created) ProtoReflect() protoreflect.Message {
	mi := &file_o5_dante_v1_dead_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadMessageEventType_Created.ProtoReflect.Descriptor instead.
func (*DeadMessageEventType_Created) Descriptor() ([]byte, []int) {
	return file_o5_dante_v1_dead_message_proto_rawDescGZIP(), []int{6, 0}
}

func (x *DeadMessageEventType_Created) GetSpec() *DeadMessageSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DeadMessageEventType_Updated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spec *DeadMessageSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *DeadMessageEventType_Updated) Reset() {
	*x = DeadMessageEventType_Updated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o5_dante_v1_dead_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeadMessageEventType_Updated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadMessageEventType_Updated) ProtoMessage() {}

func (x *DeadMessageEventType_Updated) ProtoReflect() protoreflect.Message {
	mi := &file_o5_dante_v1_dead_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadMessageEventType_Updated.ProtoReflect.Descriptor instead.
func (*DeadMessageEventType_Updated) Descriptor() ([]byte, []int) {
	return file_o5_dante_v1_dead_message_proto_rawDescGZIP(), []int{6, 1}
}

func (x *DeadMessageEventType_Updated) GetSpec() *DeadMessageSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DeadMessageEventType_Replayed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeadMessageEventType_Replayed) Reset() {
	*x = DeadMessageEventType_Replayed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o5_dante_v1_dead_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeadMessageEventType_Replayed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadMessageEventType_Replayed) ProtoMessage() {}

func (x *DeadMessageEventType_Replayed) ProtoReflect() protoreflect.Message {
	mi := &file_o5_dante_v1_dead_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadMessageEventType_Replayed.ProtoReflect.Descriptor instead.
func (*DeadMessageEventType_Replayed) Descriptor() ([]byte, []int) {
	return file_o5_dante_v1_dead_message_proto_rawDescGZIP(), []int{6, 2}
}

type DeadMessageEventType_Rejected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *DeadMessageEventType_Rejected) Reset() {
	*x = DeadMessageEventType_Rejected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_o5_dante_v1_dead_message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeadMessageEventType_Rejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadMessageEventType_Rejected) ProtoMessage() {}

func (x *DeadMessageEventType_Rejected) ProtoReflect() protoreflect.Message {
	mi := &file_o5_dante_v1_dead_message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadMessageEventType_Rejected.ProtoReflect.Descriptor instead.
func (*DeadMessageEventType_Rejected) Descriptor() ([]byte, []int) {
	return file_o5_dante_v1_dead_message_proto_rawDescGZIP(), []int{6, 3}
}

func (x *DeadMessageEventType_Rejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_o5_dante_v1_dead_message_proto protoreflect.FileDescriptor

var file_o5_dante_v1_dead_message_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6f, 0x35, 0x2f, 0x64, 0x61, 0x6e, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65,
	0x61, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x6f, 0x35, 0x2e, 0x64, 0x61, 0x6e, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62,
	0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x6f, 0x35, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f,
	0x76, 0x31, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18,
	0x70, 0x73, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x01, 0x0a, 0x10, 0x44, 0x65, 0x61,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a,
	0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x08, 0xba, 0x48, 0x05, 0x72, 0x03, 0xb0, 0x01, 0x01, 0x52, 0x09, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6f, 0x35, 0x2e, 0x64, 0x61, 0x6e, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3f, 0x0a, 0x0c, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x6f, 0x35, 0x2e, 0x64, 0x61, 0x6e, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x0b,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x70, 0x65, 0x63, 0x22, 0xae, 0x03, 0x0a, 0x0f,
	0x44, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x27, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x08, 0xba, 0x48, 0x05, 0x72, 0x03, 0xb0, 0x01, 0x01, 0x52, 0x09, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x69, 0x6e, 0x66, 0x72,
	0x61, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x71, 0x75, 0x65, 0x75, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x72, 0x70, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x39,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x35, 0x2e,
	0x64, 0x61, 0x6e, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x52, 0x0a, 0x13, 0x69, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x74, 0x5f, 0x76, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x35, 0x2e, 0x64, 0x61, 0x6e, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x56, 0x69, 0x6f, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x12, 0x69, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74,
	0x56, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x46, 0x0a, 0x0f, 0x75, 0x6e, 0x68,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x35, 0x2e, 0x64, 0x61, 0x6e, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x6e, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48,
	0x00, 0x52, 0x0e, 0x75, 0x6e, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x22, 0x8e, 0x01, 0x0a,
	0x12, 0x49, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x56, 0x69, 0x6f, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x35, 0x2e, 0x64, 0x61, 0x6e, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2e, 0x0a,
	0x07, 0x75, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14,
	0x2e, 0x6f, 0x35, 0x2e, 0x64, 0x61, 0x6e, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x72, 0x67,
	0x65, 0x6e, 0x63, 0x79, 0x52, 0x07, 0x75, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x26, 0x0a,
	0x0e, 0x55, 0x6e, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x45, 0x0a, 0x03, 0x41, 0x6e, 0x79, 0x12, 0x2a, 0x0a, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0xc9, 0x01, 0x0a,
	0x10, 0x44, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x41, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x35, 0x2e, 0x64, 0x61, 0x6e, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x42, 0x0e, 0xba, 0x48, 0x03, 0xc8,
	0x01, 0x01, 0xda, 0xe8, 0x81, 0xd9, 0x02, 0x02, 0x10, 0x01, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x10, 0xba, 0x48, 0x05, 0x72, 0x03, 0xb0,
	0x01, 0x01, 0xda, 0xe8, 0x81, 0xd9, 0x02, 0x02, 0x18, 0x01, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x41, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x35, 0x2e, 0x64, 0x61, 0x6e, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x42, 0x08, 0xda, 0xe8, 0x81, 0xd9, 0x02, 0x02, 0x08,
	0x01, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0xea, 0x03, 0x0a, 0x14, 0x44, 0x65, 0x61,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x45, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6f, 0x35, 0x2e, 0x64, 0x61, 0x6e, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x45, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6f, 0x35, 0x2e, 0x64,
	0x61, 0x6e, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12,
	0x48, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2a, 0x2e, 0x6f, 0x35, 0x2e, 0x64, 0x61, 0x6e, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x48, 0x00, 0x52,
	0x08, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x12, 0x48, 0x0a, 0x08, 0x72, 0x65, 0x6a,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6f, 0x35,
	0x2e, 0x64, 0x61, 0x6e, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x61, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x52,
	0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x6a, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x1a, 0x3b, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x30,
	0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f,
	0x35, 0x2e, 0x64, 0x61, 0x6e, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x61, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63,
	0x1a, 0x3b, 0x0a, 0x07, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x73,
	0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x35, 0x2e, 0x64,
	0x61, 0x6e, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x1a, 0x0a, 0x0a,
	0x08, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x1a, 0x22, 0x0a, 0x08, 0x52, 0x65, 0x6a,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42, 0x06, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x9a, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x23, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xba, 0x48, 0x05, 0x72, 0x03, 0xb0, 0x01, 0x01, 0x52, 0x07,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x40, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x27, 0x0a, 0x05, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6f, 0x35, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x05, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x2a, 0xa1, 0x01, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x1a, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01,
	0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17,
	0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52,
	0x45, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x44, 0x10, 0x03, 0x12, 0x1b, 0x0a, 0x17, 0x4d, 0x45, 0x53,
	0x53, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x4a, 0x45,
	0x43, 0x54, 0x45, 0x44, 0x10, 0x04, 0x2a, 0x59, 0x0a, 0x07, 0x55, 0x72, 0x67, 0x65, 0x6e, 0x63,
	0x79, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x52, 0x47, 0x45, 0x4e, 0x43, 0x59, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x52,
	0x47, 0x45, 0x4e, 0x43, 0x59, 0x5f, 0x4c, 0x4f, 0x57, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x55,
	0x52, 0x47, 0x45, 0x4e, 0x43, 0x59, 0x5f, 0x4d, 0x45, 0x44, 0x49, 0x55, 0x4d, 0x10, 0x02, 0x12,
	0x10, 0x0a, 0x0c, 0x55, 0x52, 0x47, 0x45, 0x4e, 0x43, 0x59, 0x5f, 0x48, 0x49, 0x47, 0x48, 0x10,
	0x03, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x65, 0x6e, 0x74, 0x6f, 0x70, 0x73, 0x2f, 0x6f, 0x35, 0x2d, 0x67, 0x6f, 0x2f, 0x64, 0x61,
	0x6e, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x61, 0x6e, 0x74, 0x65, 0x5f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_o5_dante_v1_dead_message_proto_rawDescOnce sync.Once
	file_o5_dante_v1_dead_message_proto_rawDescData = file_o5_dante_v1_dead_message_proto_rawDesc
)

func file_o5_dante_v1_dead_message_proto_rawDescGZIP() []byte {
	file_o5_dante_v1_dead_message_proto_rawDescOnce.Do(func() {
		file_o5_dante_v1_dead_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_o5_dante_v1_dead_message_proto_rawDescData)
	})
	return file_o5_dante_v1_dead_message_proto_rawDescData
}

var file_o5_dante_v1_dead_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_o5_dante_v1_dead_message_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_o5_dante_v1_dead_message_proto_goTypes = []interface{}{
	(MessageStatus)(0),                    // 0: o5.dante.v1.MessageStatus
	(Urgency)(0),                          // 1: o5.dante.v1.Urgency
	(*DeadMessageState)(nil),              // 2: o5.dante.v1.DeadMessageState
	(*DeadMessageSpec)(nil),               // 3: o5.dante.v1.DeadMessageSpec
	(*InvariantViolation)(nil),            // 4: o5.dante.v1.InvariantViolation
	(*UnhandledError)(nil),                // 5: o5.dante.v1.UnhandledError
	(*Any)(nil),                           // 6: o5.dante.v1.Any
	(*DeadMessageEvent)(nil),              // 7: o5.dante.v1.DeadMessageEvent
	(*DeadMessageEventType)(nil),          // 8: o5.dante.v1.DeadMessageEventType
	(*Metadata)(nil),                      // 9: o5.dante.v1.Metadata
	(*DeadMessageEventType_Created)(nil),  // 10: o5.dante.v1.DeadMessageEventType.Created
	(*DeadMessageEventType_Updated)(nil),  // 11: o5.dante.v1.DeadMessageEventType.Updated
	(*DeadMessageEventType_Replayed)(nil), // 12: o5.dante.v1.DeadMessageEventType.Replayed
	(*DeadMessageEventType_Rejected)(nil), // 13: o5.dante.v1.DeadMessageEventType.Rejected
	(*timestamppb.Timestamp)(nil),         // 14: google.protobuf.Timestamp
	(*anypb.Any)(nil),                     // 15: google.protobuf.Any
	(*auth_pb.Actor)(nil),                 // 16: o5.auth.v1.Actor
}
var file_o5_dante_v1_dead_message_proto_depIdxs = []int32{
	0,  // 0: o5.dante.v1.DeadMessageState.status:type_name -> o5.dante.v1.MessageStatus
	3,  // 1: o5.dante.v1.DeadMessageState.current_spec:type_name -> o5.dante.v1.DeadMessageSpec
	14, // 2: o5.dante.v1.DeadMessageSpec.created_at:type_name -> google.protobuf.Timestamp
	6,  // 3: o5.dante.v1.DeadMessageSpec.payload:type_name -> o5.dante.v1.Any
	4,  // 4: o5.dante.v1.DeadMessageSpec.invariant_violation:type_name -> o5.dante.v1.InvariantViolation
	5,  // 5: o5.dante.v1.DeadMessageSpec.unhandled_error:type_name -> o5.dante.v1.UnhandledError
	6,  // 6: o5.dante.v1.InvariantViolation.error:type_name -> o5.dante.v1.Any
	1,  // 7: o5.dante.v1.InvariantViolation.urgency:type_name -> o5.dante.v1.Urgency
	15, // 8: o5.dante.v1.Any.proto:type_name -> google.protobuf.Any
	9,  // 9: o5.dante.v1.DeadMessageEvent.metadata:type_name -> o5.dante.v1.Metadata
	8,  // 10: o5.dante.v1.DeadMessageEvent.event:type_name -> o5.dante.v1.DeadMessageEventType
	10, // 11: o5.dante.v1.DeadMessageEventType.created:type_name -> o5.dante.v1.DeadMessageEventType.Created
	11, // 12: o5.dante.v1.DeadMessageEventType.updated:type_name -> o5.dante.v1.DeadMessageEventType.Updated
	12, // 13: o5.dante.v1.DeadMessageEventType.replayed:type_name -> o5.dante.v1.DeadMessageEventType.Replayed
	13, // 14: o5.dante.v1.DeadMessageEventType.rejected:type_name -> o5.dante.v1.DeadMessageEventType.Rejected
	14, // 15: o5.dante.v1.Metadata.timestamp:type_name -> google.protobuf.Timestamp
	16, // 16: o5.dante.v1.Metadata.actor:type_name -> o5.auth.v1.Actor
	3,  // 17: o5.dante.v1.DeadMessageEventType.Created.spec:type_name -> o5.dante.v1.DeadMessageSpec
	3,  // 18: o5.dante.v1.DeadMessageEventType.Updated.spec:type_name -> o5.dante.v1.DeadMessageSpec
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_o5_dante_v1_dead_message_proto_init() }
func file_o5_dante_v1_dead_message_proto_init() {
	if File_o5_dante_v1_dead_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_o5_dante_v1_dead_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeadMessageState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o5_dante_v1_dead_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeadMessageSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o5_dante_v1_dead_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvariantViolation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o5_dante_v1_dead_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnhandledError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o5_dante_v1_dead_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Any); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o5_dante_v1_dead_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeadMessageEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o5_dante_v1_dead_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeadMessageEventType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o5_dante_v1_dead_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o5_dante_v1_dead_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeadMessageEventType_Created); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o5_dante_v1_dead_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeadMessageEventType_Updated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o5_dante_v1_dead_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeadMessageEventType_Replayed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_o5_dante_v1_dead_message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeadMessageEventType_Rejected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_o5_dante_v1_dead_message_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*DeadMessageSpec_InvariantViolation)(nil),
		(*DeadMessageSpec_UnhandledError)(nil),
	}
	file_o5_dante_v1_dead_message_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*DeadMessageEventType_Created_)(nil),
		(*DeadMessageEventType_Updated_)(nil),
		(*DeadMessageEventType_Replayed_)(nil),
		(*DeadMessageEventType_Rejected_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_o5_dante_v1_dead_message_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_o5_dante_v1_dead_message_proto_goTypes,
		DependencyIndexes: file_o5_dante_v1_dead_message_proto_depIdxs,
		EnumInfos:         file_o5_dante_v1_dead_message_proto_enumTypes,
		MessageInfos:      file_o5_dante_v1_dead_message_proto_msgTypes,
	}.Build()
	File_o5_dante_v1_dead_message_proto = out.File
	file_o5_dante_v1_dead_message_proto_rawDesc = nil
	file_o5_dante_v1_dead_message_proto_goTypes = nil
	file_o5_dante_v1_dead_message_proto_depIdxs = nil
}
