// Code generated by protoc-gen-go-messaging. DO NOT EDIT.

package deployer_tpb

// Service: PostgresRequestTopic
// Method: UpsertPostgresDatabase

func (msg *UpsertPostgresDatabaseMessage) MessagingTopic() string {
	return "o5-aws-command_request"
}
func (msg *UpsertPostgresDatabaseMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service":        "/o5.deployer.v1.topic.PostgresRequestTopic/UpsertPostgresDatabase",
		"grpc-message":        "o5.deployer.v1.topic.UpsertPostgresDatabaseMessage",
		"o5-request-reply-to": msg.Request.ReplyTo,
	}
	return headers
}

// Method: MigratePostgresDatabase

func (msg *MigratePostgresDatabaseMessage) MessagingTopic() string {
	return "o5-aws-command_request"
}
func (msg *MigratePostgresDatabaseMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service":        "/o5.deployer.v1.topic.PostgresRequestTopic/MigratePostgresDatabase",
		"grpc-message":        "o5.deployer.v1.topic.MigratePostgresDatabaseMessage",
		"o5-request-reply-to": msg.Request.ReplyTo,
	}
	return headers
}

// Method: CleanupPostgresDatabase

func (msg *CleanupPostgresDatabaseMessage) MessagingTopic() string {
	return "o5-aws-command_request"
}
func (msg *CleanupPostgresDatabaseMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service":        "/o5.deployer.v1.topic.PostgresRequestTopic/CleanupPostgresDatabase",
		"grpc-message":        "o5.deployer.v1.topic.CleanupPostgresDatabaseMessage",
		"o5-request-reply-to": msg.Request.ReplyTo,
	}
	return headers
}

// Service: PostgresReplyTopic
// Method: PostgresDatabaseStatus

func (msg *PostgresDatabaseStatusMessage) MessagingTopic() string {
	return "o5-aws-command_reply"
}
func (msg *PostgresDatabaseStatusMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service":      "/o5.deployer.v1.topic.PostgresReplyTopic/PostgresDatabaseStatus",
		"grpc-message":      "o5.deployer.v1.topic.PostgresDatabaseStatusMessage",
		"o5-reply-reply-to": msg.Request.ReplyTo,
	}
	return headers
}
