// Code generated by protoc-gen-go-messaging. DO NOT EDIT.

package deployer_tpb

// Service: CloudFormationRequestTopic
// Method: CreateNewStack

func (msg *CreateNewStackMessage) MessagingTopic() string {
	return "o5-aws-command_request"
}
func (msg *CreateNewStackMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service":        "/o5.deployer.v1.topic.CloudFormationRequestTopic/CreateNewStack",
		"grpc-message":        "o5.deployer.v1.topic.CreateNewStackMessage",
		"o5-request-reply-to": msg.Request.ReplyTo,
	}
	return headers
}

// Method: UpdateStack

func (msg *UpdateStackMessage) MessagingTopic() string {
	return "o5-aws-command_request"
}
func (msg *UpdateStackMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service":        "/o5.deployer.v1.topic.CloudFormationRequestTopic/UpdateStack",
		"grpc-message":        "o5.deployer.v1.topic.UpdateStackMessage",
		"o5-request-reply-to": msg.Request.ReplyTo,
	}
	return headers
}

// Method: DeleteStack

func (msg *DeleteStackMessage) MessagingTopic() string {
	return "o5-aws-command_request"
}
func (msg *DeleteStackMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service":        "/o5.deployer.v1.topic.CloudFormationRequestTopic/DeleteStack",
		"grpc-message":        "o5.deployer.v1.topic.DeleteStackMessage",
		"o5-request-reply-to": msg.Request.ReplyTo,
	}
	return headers
}

// Method: ScaleStack

func (msg *ScaleStackMessage) MessagingTopic() string {
	return "o5-aws-command_request"
}
func (msg *ScaleStackMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service":        "/o5.deployer.v1.topic.CloudFormationRequestTopic/ScaleStack",
		"grpc-message":        "o5.deployer.v1.topic.ScaleStackMessage",
		"o5-request-reply-to": msg.Request.ReplyTo,
	}
	return headers
}

// Method: CancelStackUpdate

func (msg *CancelStackUpdateMessage) MessagingTopic() string {
	return "o5-aws-command_request"
}
func (msg *CancelStackUpdateMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service":        "/o5.deployer.v1.topic.CloudFormationRequestTopic/CancelStackUpdate",
		"grpc-message":        "o5.deployer.v1.topic.CancelStackUpdateMessage",
		"o5-request-reply-to": msg.Request.ReplyTo,
	}
	return headers
}

// Method: StabalizeStack

func (msg *StabalizeStackMessage) MessagingTopic() string {
	return "o5-aws-command_request"
}
func (msg *StabalizeStackMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service":        "/o5.deployer.v1.topic.CloudFormationRequestTopic/StabalizeStack",
		"grpc-message":        "o5.deployer.v1.topic.StabalizeStackMessage",
		"o5-request-reply-to": msg.Request.ReplyTo,
	}
	return headers
}

// Service: CloudFormationReplyTopic
// Method: StackStatusChanged

func (msg *StackStatusChangedMessage) MessagingTopic() string {
	return "o5-aws-command_reply"
}
func (msg *StackStatusChangedMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service":      "/o5.deployer.v1.topic.CloudFormationReplyTopic/StackStatusChanged",
		"grpc-message":      "o5.deployer.v1.topic.StackStatusChangedMessage",
		"o5-reply-reply-to": msg.Request.ReplyTo,
	}
	return headers
}
