// Code generated by protoc-gen-go-messaging. DO NOT EDIT.

package deployer_tpb

// Service: DeployerTopic
// Method: TriggerDeployment

func (msg *TriggerDeploymentMessage) MessagingTopic() string {
	return "o5-deployer-input"
}
func (msg *TriggerDeploymentMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service": "/o5.deployer.v1.topic.DeployerTopic/TriggerDeployment",
		"grpc-message": "o5.deployer.v1.topic.TriggerDeploymentMessage",
	}
	return headers
}

// Method: StackStatusChanged

func (msg *StackStatusChangedMessage) MessagingTopic() string {
	return "o5-deployer-input"
}
func (msg *StackStatusChangedMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service": "/o5.deployer.v1.topic.DeployerTopic/StackStatusChanged",
		"grpc-message": "o5.deployer.v1.topic.StackStatusChangedMessage",
	}
	return headers
}

// Method: MigrationStatusChanged

func (msg *MigrationStatusChangedMessage) MessagingTopic() string {
	return "o5-deployer-input"
}
func (msg *MigrationStatusChangedMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service": "/o5.deployer.v1.topic.DeployerTopic/MigrationStatusChanged",
		"grpc-message": "o5.deployer.v1.topic.MigrationStatusChangedMessage",
	}
	return headers
}
