// Code generated by protoc-gen-go-sugar. DO NOT EDIT.

package deployer_tpb

import (
	driver "database/sql/driver"
	fmt "fmt"
)

// DeploymentStatus
const (
	DeploymentStatus_UNSPECIFIED DeploymentStatus = 0
	DeploymentStatus_PENDING     DeploymentStatus = 1
	DeploymentStatus_IN_PROGRESS DeploymentStatus = 2
	DeploymentStatus_SUCCESS     DeploymentStatus = 3
	DeploymentStatus_FAILED      DeploymentStatus = 4
)

var (
	DeploymentStatus_name_short = map[int32]string{
		0: "UNSPECIFIED",
		1: "PENDING",
		2: "IN_PROGRESS",
		3: "SUCCESS",
		4: "FAILED",
	}
	DeploymentStatus_value_short = map[string]int32{
		"UNSPECIFIED": 0,
		"PENDING":     1,
		"IN_PROGRESS": 2,
		"SUCCESS":     3,
		"FAILED":      4,
	}
	DeploymentStatus_value_either = map[string]int32{
		"UNSPECIFIED":                   0,
		"DEPLOYMENT_STATUS_UNSPECIFIED": 0,
		"PENDING":                       1,
		"DEPLOYMENT_STATUS_PENDING":     1,
		"IN_PROGRESS":                   2,
		"DEPLOYMENT_STATUS_IN_PROGRESS": 2,
		"SUCCESS":                       3,
		"DEPLOYMENT_STATUS_SUCCESS":     3,
		"FAILED":                        4,
		"DEPLOYMENT_STATUS_FAILED":      4,
	}
)

// ShortString returns the un-prefixed string representation of the enum value
func (x DeploymentStatus) ShortString() string {
	return DeploymentStatus_name_short[int32(x)]
}
func (x DeploymentStatus) Value() (driver.Value, error) {
	return []uint8(x.ShortString()), nil
}
func (x *DeploymentStatus) Scan(value interface{}) error {
	var strVal string
	switch vt := value.(type) {
	case []uint8:
		strVal = string(vt)
	case string:
		strVal = vt
	default:
		return fmt.Errorf("invalid type %T", value)
	}
	val := DeploymentStatus_value_either[strVal]
	*x = DeploymentStatus(val)
	return nil
}
