// Code generated by protoc-gen-go-messaging. DO NOT EDIT.

package deployer_tpb

// Service: DeploymentRequestTopic
// Method: RequestDeployment

func (msg *RequestDeploymentMessage) MessagingTopic() string {
	return "o5-deployer-input_request"
}
func (msg *RequestDeploymentMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service": "/o5.deployer.v1.topic.DeploymentRequestTopic/RequestDeployment",
		"grpc-message": "o5.deployer.v1.topic.RequestDeploymentMessage",
	}
	if msg.Metadata != nil {
		headers["o5-request-reply-to"] = msg.Metadata.ReplyTo
	}
	return headers
}

// Service: DeploymentReplyTopic
// Method: DeploymentStatus

func (msg *DeploymentStatusMessage) MessagingTopic() string {
	return "o5-deployer-output_reply"
}
func (msg *DeploymentStatusMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service": "/o5.deployer.v1.topic.DeploymentReplyTopic/DeploymentStatus",
		"grpc-message": "o5.deployer.v1.topic.DeploymentStatusMessage",
	}
	if msg.Metadata != nil {
		headers["o5-reply-reply-to"] = msg.Metadata.ReplyTo
	}
	return headers
}
