// Code generated by protoc-gen-go-sugar. DO NOT EDIT.

package deployer_pb

type IsParameterSourceType_Type = isParameterSourceType_Type
type IsCloudFormationStackParameter_Source = isCloudFormationStackParameter_Source
type IsCloudFormationStackParameterType_Type = isCloudFormationStackParameterType_Type
