// Code generated by protoc-gen-go-psm. DO NOT EDIT.

package deployer_pb

import (
	context "context"
	fmt "fmt"
	psm "github.com/pentops/protostate/psm"
	sqrlx "github.com/pentops/sqrlx.go/sqrlx"
	proto "google.golang.org/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// StateObjectOptions: EnvironmentPSM
type EnvironmentPSM = psm.StateMachine[
	*EnvironmentState,
	EnvironmentStatus,
	*EnvironmentEvent,
	EnvironmentPSMEvent,
]

type EnvironmentPSMDB = psm.DBStateMachine[
	*EnvironmentState,
	EnvironmentStatus,
	*EnvironmentEvent,
	EnvironmentPSMEvent,
]

type EnvironmentPSMEventer = psm.Eventer[
	*EnvironmentState,
	EnvironmentStatus,
	*EnvironmentEvent,
	EnvironmentPSMEvent,
]

func DefaultEnvironmentPSMConfig() *psm.StateMachineConfig[
	*EnvironmentState,
	EnvironmentStatus,
	*EnvironmentEvent,
	EnvironmentPSMEvent,
] {
	return psm.NewStateMachineConfig[
		*EnvironmentState,
		EnvironmentStatus,
		*EnvironmentEvent,
		EnvironmentPSMEvent,
	](EnvironmentPSMConverter{}, DefaultEnvironmentPSMTableSpec)
}

func NewEnvironmentPSM(config *psm.StateMachineConfig[
	*EnvironmentState,
	EnvironmentStatus,
	*EnvironmentEvent,
	EnvironmentPSMEvent,
]) (*EnvironmentPSM, error) {
	return psm.NewStateMachine[
		*EnvironmentState,
		EnvironmentStatus,
		*EnvironmentEvent,
		EnvironmentPSMEvent,
	](config)
}

type EnvironmentPSMTableSpec = psm.PSMTableSpec[
	*EnvironmentState,
	EnvironmentStatus,
	*EnvironmentEvent,
	EnvironmentPSMEvent,
]

var DefaultEnvironmentPSMTableSpec = EnvironmentPSMTableSpec{
	State: psm.TableSpec[*EnvironmentState]{
		TableName:  "environment",
		DataColumn: "state",
		StoreExtraColumns: func(state *EnvironmentState) (map[string]interface{}, error) {
			return map[string]interface{}{}, nil
		},
		PKFieldPaths: []string{
			"environment_id",
		},
	},
	Event: psm.TableSpec[*EnvironmentEvent]{
		TableName:  "environment_event",
		DataColumn: "data",
		StoreExtraColumns: func(event *EnvironmentEvent) (map[string]interface{}, error) {
			metadata := event.Metadata
			return map[string]interface{}{
				"id":             metadata.EventId,
				"timestamp":      metadata.Timestamp,
				"actor":          metadata.Actor,
				"environment_id": event.EnvironmentId,
			}, nil
		},
		PKFieldPaths: []string{
			"metadata.event_id",
		},
		PK: func(event *EnvironmentEvent) (map[string]interface{}, error) {
			return map[string]interface{}{
				"id": event.Metadata.EventId,
			}, nil
		},
	},
	PrimaryKey: func(event *EnvironmentEvent) (map[string]interface{}, error) {
		return map[string]interface{}{
			"id": event.EnvironmentId,
		}, nil
	},
}

type EnvironmentPSMTransitionBaton = psm.TransitionBaton[*EnvironmentEvent, EnvironmentPSMEvent]
type EnvironmentPSMHookBaton = psm.StateHookBaton[*EnvironmentEvent, EnvironmentPSMEvent]

func EnvironmentPSMFunc[SE EnvironmentPSMEvent](cb func(context.Context, EnvironmentPSMTransitionBaton, *EnvironmentState, SE) error) psm.PSMCombinedFunc[
	*EnvironmentState,
	EnvironmentStatus,
	*EnvironmentEvent,
	EnvironmentPSMEvent,
	SE,
] {
	return psm.PSMCombinedFunc[
		*EnvironmentState,
		EnvironmentStatus,
		*EnvironmentEvent,
		EnvironmentPSMEvent,
		SE,
	](cb)
}
func EnvironmentPSMTransition[SE EnvironmentPSMEvent](cb func(context.Context, *EnvironmentState, SE) error) psm.PSMTransitionFunc[
	*EnvironmentState,
	EnvironmentStatus,
	*EnvironmentEvent,
	EnvironmentPSMEvent,
	SE,
] {
	return psm.PSMTransitionFunc[
		*EnvironmentState,
		EnvironmentStatus,
		*EnvironmentEvent,
		EnvironmentPSMEvent,
		SE,
	](cb)
}
func EnvironmentPSMHook[SE EnvironmentPSMEvent](cb func(context.Context, sqrlx.Transaction, EnvironmentPSMHookBaton, *EnvironmentState, SE) error) psm.PSMHookFunc[
	*EnvironmentState,
	EnvironmentStatus,
	*EnvironmentEvent,
	EnvironmentPSMEvent,
	SE,
] {
	return psm.PSMHookFunc[
		*EnvironmentState,
		EnvironmentStatus,
		*EnvironmentEvent,
		EnvironmentPSMEvent,
		SE,
	](cb)
}
func EnvironmentPSMGeneralHook(cb func(context.Context, sqrlx.Transaction, *EnvironmentState, *EnvironmentEvent) error) psm.GeneralStateHook[
	*EnvironmentState,
	EnvironmentStatus,
	*EnvironmentEvent,
	EnvironmentPSMEvent,
] {
	return psm.GeneralStateHook[
		*EnvironmentState,
		EnvironmentStatus,
		*EnvironmentEvent,
		EnvironmentPSMEvent,
	](cb)
}

type EnvironmentPSMEventKey = string

const (
	EnvironmentPSMEventNil        EnvironmentPSMEventKey = "<nil>"
	EnvironmentPSMEventConfigured EnvironmentPSMEventKey = "configured"
)

type EnvironmentPSMEvent interface {
	proto.Message
	PSMEventKey() EnvironmentPSMEventKey
}

type EnvironmentPSMConverter struct{}

func (c EnvironmentPSMConverter) EmptyState(e *EnvironmentEvent) *EnvironmentState {
	return &EnvironmentState{
		EnvironmentId: e.EnvironmentId,
	}
}

func (c EnvironmentPSMConverter) DeriveChainEvent(e *EnvironmentEvent, systemActor psm.SystemActor, eventKey string) *EnvironmentEvent {
	metadata := &EventMetadata{
		EventId:   systemActor.NewEventID(e.Metadata.EventId, eventKey),
		Timestamp: timestamppb.Now(),
	}
	actorProto := systemActor.ActorProto()
	refl := metadata.ProtoReflect()
	refl.Set(refl.Descriptor().Fields().ByName("actor"), actorProto)
	return &EnvironmentEvent{
		Metadata:      metadata,
		EnvironmentId: e.EnvironmentId,
	}
}

func (c EnvironmentPSMConverter) CheckStateKeys(s *EnvironmentState, e *EnvironmentEvent) error {
	if s.EnvironmentId != e.EnvironmentId {
		return fmt.Errorf("state field 'EnvironmentId' %q does not match event field %q", s.EnvironmentId, e.EnvironmentId)
	}
	return nil
}

func (etw *EnvironmentEventType) UnwrapPSMEvent() EnvironmentPSMEvent {
	if etw == nil {
		return nil
	}
	switch v := etw.Type.(type) {
	case *EnvironmentEventType_Configured_:
		return v.Configured
	default:
		return nil
	}
}
func (etw *EnvironmentEventType) PSMEventKey() EnvironmentPSMEventKey {
	tt := etw.UnwrapPSMEvent()
	if tt == nil {
		return EnvironmentPSMEventNil
	}
	return tt.PSMEventKey()
}
func (etw *EnvironmentEventType) SetPSMEvent(inner EnvironmentPSMEvent) {
	switch v := inner.(type) {
	case *EnvironmentEventType_Configured:
		etw.Type = &EnvironmentEventType_Configured_{Configured: v}
	default:
		panic("invalid type")
	}
}

func (ee *EnvironmentEvent) PSMEventKey() EnvironmentPSMEventKey {
	return ee.Event.PSMEventKey()
}

func (ee *EnvironmentEvent) UnwrapPSMEvent() EnvironmentPSMEvent {
	return ee.Event.UnwrapPSMEvent()
}

func (ee *EnvironmentEvent) SetPSMEvent(inner EnvironmentPSMEvent) {
	if ee.Event == nil {
		ee.Event = &EnvironmentEventType{}
	}
	ee.Event.SetPSMEvent(inner)
}

func (*EnvironmentEventType_Configured) PSMEventKey() EnvironmentPSMEventKey {
	return EnvironmentPSMEventConfigured
}
