// Code generated by protoc-gen-go-sugar. DO NOT EDIT.

package deployer_pb

import (
	driver "database/sql/driver"
	fmt "fmt"
)

type IsStackEventType_Type = isStackEventType_Type

// StackStatus
const (
	StackStatus_UNSPECIFIED StackStatus = 0
	StackStatus_CREATING    StackStatus = 1
	StackStatus_STABLE      StackStatus = 2
	StackStatus_AVAILABLE   StackStatus = 3
	StackStatus_MIGRATING   StackStatus = 4
	StackStatus_BROKEN      StackStatus = 5
)

var (
	StackStatus_name_short = map[int32]string{
		0: "UNSPECIFIED",
		1: "CREATING",
		2: "STABLE",
		3: "AVAILABLE",
		4: "MIGRATING",
		5: "BROKEN",
	}
	StackStatus_value_short = map[string]int32{
		"UNSPECIFIED": 0,
		"CREATING":    1,
		"STABLE":      2,
		"AVAILABLE":   3,
		"MIGRATING":   4,
		"BROKEN":      5,
	}
	StackStatus_value_either = map[string]int32{
		"UNSPECIFIED":              0,
		"STACK_STATUS_UNSPECIFIED": 0,
		"CREATING":                 1,
		"STACK_STATUS_CREATING":    1,
		"STABLE":                   2,
		"STACK_STATUS_STABLE":      2,
		"AVAILABLE":                3,
		"STACK_STATUS_AVAILABLE":   3,
		"MIGRATING":                4,
		"STACK_STATUS_MIGRATING":   4,
		"BROKEN":                   5,
		"STACK_STATUS_BROKEN":      5,
	}
)

// ShortString returns the un-prefixed string representation of the enum value
func (x StackStatus) ShortString() string {
	return StackStatus_name_short[int32(x)]
}
func (x StackStatus) Value() (driver.Value, error) {
	return []uint8(x.ShortString()), nil
}
func (x *StackStatus) Scan(value interface{}) error {
	var strVal string
	switch vt := value.(type) {
	case []uint8:
		strVal = string(vt)
	case string:
		strVal = vt
	default:
		return fmt.Errorf("invalid type %T", value)
	}
	val := StackStatus_value_either[strVal]
	*x = StackStatus(val)
	return nil
}
