// Code generated by protoc-gen-go-messaging. DO NOT EDIT.

package messaging_tpb

import (
	messaging_pb "github.com/pentops/o5-go/messaging/v1/messaging_pb"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// Service: DeadMessageTopic
// Method: Dead

func (msg *DeadMessage) O5Message(id string) (*messaging_pb.Message, error) {
	body, err := protojson.Marshal(msg)
	if err != nil {
		return nil, err
	}
	return &messaging_pb.Message{
		DestinationTopic: "dead-letter",
		MessageId:        id,
		GrpcService:      "o5.messaging.v1.topic.DeadMessageTopic",
		GrpcMethod:       "Dead",
		Body: &messaging_pb.Any{
			TypeUrl:  "type.googleapis.com/o5.messaging.v1.topic.DeadMessage",
			Value:    body,
			Encoding: messaging_pb.WireEncoding_WIRE_ENCODING_PROTOJSON,
		},
		Headers: map[string]string{},
	}, nil
}

func (msg *DeadMessage) MessagingTopic() string {
	return "dead-letter"
}
func (msg *DeadMessage) MessagingHeaders() map[string]string {
	headers := map[string]string{
		"grpc-service": "/o5.messaging.v1.topic.DeadMessageTopic/Dead",
		"grpc-message": "o5.messaging.v1.topic.DeadMessage",
	}
	return headers
}
